#ifndef CONSTS_H
#define CONSTS_H

typedef enum COMMANDS_IDX
{
    COMMAND_MOV = 0,
    COMMAND_CMP,
    COMMAND_ADD,
    COMMAND_SUB,
    COMMAND_LEA,
    COMMAND_CLR,
    COMMAND_NOT,
    COMMAND_INC,
    COMMAND_DEC,
    COMMAND_JMP,
    COMMAND_BNE,
    COMMAND_JSR,
    COMMAND_RED,
    COMMAND_PRN,
    COMMAND_RTS,
    COMMAND_STOP
} COMMANDS_IDX;

typedef enum GUIDES_IDX
{
    GUIDE_DATA = 0,
    GUIDE_STRING,
    GUIDE_MAT,
    GUIDE_ENTRY,
    GUIDE_EXTERN
} GUIDES_IDX;

typedef enum REGISTERS_IDX
{
    REGISTER_R0 = 0,
    REGISTER_R1,
    REGISTER_R2,
    REGISTER_R3,
    REGISTER_R4,
    REGISTER_R5,
    REGISTER_R6,
    REGISTER_R7
} REGISTERS_IDX;

typedef enum ALLOCATION_TYPES
{
    ALLOCATION_MISSING = -1,
    ALLOCATION_IMMEDIATE = 0,
    ALLOCATION_DIRECT,
    ALLOCATION_MAT,
    ALLOCATION_REGISTER,
    ALLOCATION_INVALID
} ALLOCATION_TYPES;

typedef enum ARE_TYPES
{
    ABSOLUTE_CODE,
    EXTERNAL_CODE,
    RELOCATABLE_CODE
} ARE_TYPES;

#define LABEL_SIZE 31
#define LINE_SIZE 80
#define BINARY_CODE_SIZE 11
#define REG_SIZE 3

#endif
