#ifndef CONSTS_H
#define CONSTS_H

typedef enum OPERATIONS_IDX
{
    OPERATION_MOV = 0,
    OPERATION_CMP,
    OPERATION_ADD,
    OPERATION_SUB,
    OPERATION_LEA,
    OPERATION_CLR,
    OPERATION_NOT,
    OPERATION_INC,
    OPERATION_DEC,
    OPERATION_JMP,
    OPERATION_BNE,
    OPERATION_JSR,
    OPERATION_RED,
    OPERATION_PRN,
    OPERATION_RTS,
    OPERATION_STOP,
} OPERATIONS_IDX;

typedef enum GUIDES_IDX
{
    GUIDE_DATA = 0,
    GUIDE_STRING,
    GUIDE_MAT,
    GUIDE_ENTRY,
    GUIDE_EXTERN,
} GUIDES_IDX;

typedef enum ALLOCATION_TYPES
{
    ALLOCATION_MISSING = -1,
    ALLOCATION_IMMEDIATE = 0,
    ALLOCATION_DIRECT,
    ALLOCATION_MAT,
    ALLOCATION_REGISTER
} ALLOCATION_TYPES;

#endif
