typedef enum PROCESS_ERROR_CODES
{
    /* internal */
    PROCESS_ERROR_MEMORY_ALLOCATION_FAILED,
    /* mcro */
    PROCESS_ERROR_INVALID_MACRO_NAME,
    PROCESS_ERROR_INVALID_MACRO_DECLARATION,
    PROCESS_ERROR_INVALID_MACRO_END_DECLARATION,
    /* files */
    PROCESS_ERROR_FAILED_TO_OPEN_FILE
} PROCESS_ERROR_CODES;
